### ISSUE TITLE
Local Fonts Aren't Visible on Page Load

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-text-style#21]
BUG: If a local font is your default font when the page loads, it's not visible from within the preview until you change the font back and forth.

**Comment by themoonrat** [comment]
I have a solution for this in my slightly customised version; I use FontFaceObserver to load the font, then refresh the text when it says it's loaded.

```
const ffo = new FontFaceObserver( customFont );
    ffo.load().then( () => {
    this.text.updateText();
    this.app.render();
} );
```

I'll see if I can port that over to this

**Comment by jonlepage** [comment]
hum, it was worked on my side locally , it strange, i will take a look, sorry for that's.

**Comment by jonlepage** [comment]
i think it can came from here. (my theory)
https://github.com/pixijs/pixi-text-style/blob/80b06ee3ac45d3dac2eb135c0619be7249b73871/src/TextStyleEditor.jsx#L123
Maybe need a `await` somewhere or move out `document.createElement('option')` because it async and i think the page try focus or rendering **on a empty options** before it created ? maybe.
https://github.com/pixijs/pixi-text-style/blob/80b06ee3ac45d3dac2eb135c0619be7249b73871/src/components/FontsLoader.jsx#L67
So it maybe related to this strange message
![image](https://user-images.githubusercontent.com/24865815/72473177-20135400-37b4-11ea-9d14-1218abb0d41d.png)
BTW, there is a logical bug on this part, that portion needs to be rethought more cleaner.
I had developed it a little blind.

**Comment by bigtimebuddy** [comment]
It’s a race condition. The text is rendered before the font is loaded. We need to force update the text and render after the font is loaded.

**Comment by jonlepage** [comment]
> It’s a race condition. 

you just learning me a new strange word in english ! cool!
https://en.wikipedia.org/wiki/Race_condition
